List<Map<String, dynamic>> PlayStoreApp_Data = [
  {
    "name": "Instagram",
    "logo": "instagram.png",
    "category": "Communication",
    "size": "264 MB",
    "ratings": "4.4",
  },
  {
    "name": "Facebook",
    "logo": "facebook.png",
    "category": "Communication",
    "size": "233 MB",
    "ratings": "4.1",
  },
  {
    "name": "Whatsapp",
    "logo": "whatsapp.png",
    "category": "Communication",
    "size": "240 MB",
    "ratings": "4.5",
  },
  {
    "name": "Instagram",
    "logo": "instagram.png",
    "category": "Communication",
    "size": "264 MB",
    "ratings": "4.4",
  },
  {
    "name": "Instagram",
    "logo": "instagram.png",
    "category": "Communication",
    "size": "264 MB",
    "ratings": "4.4",
  },
  {
    "name": "Instagram",
    "logo": "instagram.png",
    "category": "Communication",
    "size": "264 MB",
    "ratings": "4.4",
  },
  {
    "name": "Instagram",
    "logo": "instagram.png",
    "category": "Communication",
    "size": "264 MB",
    "ratings": "4.4",
  },
  {
    "name": "Instagram",
    "logo": "instagram.png",
    "category": "Communication",
    "size": "264 MB",
    "ratings": "4.4",
  },
];
