List<Map<String, dynamic>> PlayStoreApp_Data = [
  {
    "name": "Instagram",
    "logo": "instagram.png",
    "category": "Communication",
    "size": "264 MB",
    "ratings": "4.4",
  },
  {
    "name": "Facebook",
    "logo": "facebook.png",
    "category": "Communication",
    "size": "233 MB",
    "ratings": "4.1",
  },
  {
    "name": "Whatsapp",
    "logo": "whatsapp.png",
    "category": "Communication",
    "size": "240 MB",
    "ratings": "4.5",
  },
  {
    "name": "Notes",
    "logo": "notes.png",
    "category": "Productivity",
    "size": "64 MB",
    "ratings": "4.1",
  },
  {
    "name": "Linkedin",
    "logo": "linkedin.png",
    "category": "Communication",
    "size": "264 MB",
    "ratings": "3.0",
  },
  {
    "name": "Ecommerce",
    "logo": "ecommerce.png",
    "category": "Business",
    "size": "264 MB",
    "ratings": "4.0",
  },
  {
    "name": "Mero Tution",
    "logo": "study.png",
    "category": "Educational",
    "size": "264 MB",
    "ratings": "4.7",
  },
  {
    "name": "Viber",
    "logo": "viber.png",
    "category": "Communication",
    "size": "264 MB",
    "ratings": "3.1",
  },
  {
    "name": "Twitter",
    "logo": "twitter.png",
    "category": "Communication",
    "size": "264 MB",
    "ratings": "3.7",
  },
  {
    "name": "Tiktok",
    "logo": "tiktok.png",
    "category": "Communication",
    "size": "33 MB",
    "ratings": "3.4",
  },
  {
    "name": "Mero Quiz",
    "logo": "quiz.png",
    "category": "Educational",
    "size": "64 MB",
    "ratings": "4.9",
  },
  {
    "name": "Calculator",
    "logo": "calculator.png",
    "category": "Educational",
    "size": "264 MB",
    "ratings": "4.4",
  },
  {
    "name": "Business Card",
    "logo": "card.png",
    "category": "Business",
    "size": "24 MB",
    "ratings": "3.9",
  },
  {
    "name": "Mero Music",
    "logo": "music.png",
    "category": "Entertainment",
    "size": "10 MB",
    "ratings": "3.5",
  },
];
